# JupyterBook settings. See https://jupyterbook.org/customize/config.html

title: SNN Sound Localization
author: "COMOB, the project for collaborative modelling of the brain"
  # This is used by jb in the footer (prefixed by "By ")

execute:
  execute_notebooks: "off"
    # Do not try to re-run notebooks when building the website. Rather use images and
    # other outputs already embedded in the notebook.

only_build_toc_files: false
  # We want to build the code of conduct (have it be linkable to on website), but not have it in TOC.

exclude_patterns: [.github/*, ReadMe.md, web/ReadMe.md]  # .. but do not build the files here

# bibtex_bibfiles:
  # - references.bib

html:
  baseurl: https://comob-project.github.io/snn-sound-localization
  favicon: web/headphone-logo.png
  home_page_in_navbar:   true
  extra_navbar: ""               # Text under TOC. Default: "Powered by JupyterBook".
  extra_footer: |
    <small>
      Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA</a>:
      You may use this work, with attribution, in other freely available works.
    </small>
  use_repository_button: true    # gh logo, click to go to repo
  use_issues_button:     false   # "Open issue" button in gh logo dropdown
  use_edit_page_button:  true    # "Suggest edit" button in gh logo dropdown.
  comments:
    hypothesis: true             # Adds the Hypothesis script to every page, which adds
                                 # a sidebar, for in-situ comments.

repository:
  url: https://github.com/comob-project/snn-sound-localization
  branch: main
# The `repository` settings are used by jb to create a link to the source of a web-page
# (i.e. the underlying .ipynb or .md file) -- used for the "Suggest edit" button under
# the gh logo.

launch_buttons:
  colab_url: https://colab.research.google.com
  # (Binder button is enabled by default).

sphinx:
  config:
    html_show_copyright: false   # Remove "© Copyright 2022." in footer
    html_static_path: ["web/_static"]  # default is `_static`, but cleaner to hide in `web/`.
